/** Declaration file generated by dts-gen */

export = WavefrontObjParser;

declare function WavefrontObjParser(wavefrontString: string): WavefrontObjParser.ResultJSON;

declare namespace WavefrontObjParser {
    const prototype: {
    };

    interface ResultJSON {
      normal: number[];
      uv: number[];
      vertex: number[];
      normalIndex: number[];
      uvIndex: number[];
      vertexIndex: number[];
    }
}
